### ISSUE TITLE
Feature Request: Provide support for MQTT client authentication

### ISSUE THREAD

**Issue by Automayted** [zwily/lutron-pro-hub-mqtt#5]
Would it be possible to add support for MQTT client authentication? 

Ideally users could add `--mqtt-user` and `--mqtt-pass` to the docker run command.

Thanks!

**Comment by Vansmak** [comment]
2nd, its kinda useless for me without user and pass for my mqtt broker

**Comment by zwily** [comment]
I’m happy to take a pull request!

**Comment by zwily** [comment]
Actually, looking at the mqtt code, you can probably specify username and password in your URL, like: `mqtt://username:password@host.name/`. Does someone want to try it out?

**Comment by Automayted** [comment]
> Actually, looking at the mqtt code, you can probably specify username and password in your URL, like: `mqtt://username:password@host.name/`. Does someone want to try it out?

Success! Thanks so much for looking into this and apologies for not digging in further myself.
